name: Build APP
run-name: ${{ github.actor }} is building application using github actions.
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - run: echo "🍏 This job's status is ${{ job.status }}."
